name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test
      id: test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: test
        setup-command: ''
        command: javac secondLargest.java && java secondLargest
        input: |-
          5
          25
          68
          97
          44
          73
        expected-output: |-
          PROGRAM FOR FINDING THE SECOND HIGHEST NUMBER IN AN ARRAY

          ENTER THE SIZE OF THE ARRAY
          ENTER THE ELEMENTS OF THE ARRAY
          The Second Highest Number is 73
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
      with:
        runners: test
